version: '3.10'
services:
  database:
    container_name: database
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - default
    expose:
      - "5432"

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    command: sh -c "/wait && /app/main"
    networks:
      - default
    ports:
    - 8080:8080
volumes:
  data:
